/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('sounds').del();
  await knex('sounds').insert([
    {
      id: 1,
      name: 'US_RD_121_Bass_3AM_Fm',
      type: 'bass',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Fm',
      rel_key_scale: 'A',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_121_Bass_3AM_Fm.wav",
    },
    {
      id: 2,
      name: 'US_RD_121_Bass_90s_Dm',
      type: 'bass',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Dm',
      rel_key_scale: 'F',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_121_Bass_90s_Dm.wav",
    },
    {
      id: 3,
      name: 'US_RD_121_Bass_Ayres_Em',
      type: 'bass',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Em',
      rel_key_scale: 'G',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_121_Bass_Ayres_Em.wav",
    },
    {
      id: 4,
      name: 'US_RD_121_Bass_barbara_A#m',
      type: 'bass',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'A#m',
      rel_key_scale: 'C#',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_121_Bass_barbara_A#m.wav",
    },
    {
      id: 5,
      name: 'US_RD_121_Bass_barcelona_Am',
      type: 'bass',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Fm',
      rel_key_scale: 'G#',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_121_Bass_barcelona_Am.wav",
    },
    {
      id: 6,
      name: 'US_RD_121_Acamar_A',
      type: 'chords',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'A',
      rel_key_scale: 'F#m',
      bpm: 121,
      length: 8,
      url: "http://localhost:8080/audio/US_RD_121_Acamar_A.wav",
    },
    {
      id: 7,
      name: 'US_RD_121_Achird_Dm',
      type: 'chords',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Dm',
      rel_key_scale: 'F',
      bpm: 121,
      length: 8,
      url: "http://localhost:8080/audio/US_RD_121_Achird_Dm.wav",
    },
    {
      id: 8,
      name: 'US_RD_121_Acrab_Bm',
      type: 'chords',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Bm',
      rel_key_scale: 'D',
      bpm: 121,
      length: 8,
      url: "http://localhost:8080/audio/US_RD_121_Acrab_Bm.wav",
    },
    {
      id: 9,
      name: 'US_RD_121_Acrux_Cm',
      type: 'chords',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Cm',
      rel_key_scale: 'D#',
      bpm: 121,
      length: 8,
      url: "http://localhost:8080/audio/US_RD_121_Acrux_Cm.wav",
    },
    {
      id: 10,
      name: 'US_RD_121_Acubens_A',
      type: 'chords',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'A',
      rel_key_scale: 'F#m',
      bpm: 121,
      length: 8,
      url: "http://localhost:8080/audio/US_RD_121_Acubens_A.wav",
    },
    {
      id: 11,
      name: 'US_RD_BEAT_121_909',
      type: 'drums',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: '',
      rel_key_scale: '',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_BEAT_121_909.wav",
    },
    {
      id: 12,
      name: 'US_RD_BEAT_121_BEAT',
      type: 'drums',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: '',
      rel_key_scale: '',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_BEAT_121_BEAT.wav",
    },
    {
      id: 13,
      name: 'US_RD_BEAT_121_DRUGS',
      type: 'drums',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: '',
      rel_key_scale: '',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_BEAT_121_DRUGS.wav",
    },
    {
      id: 14,
      name: 'US_RD_BEAT_121_EURO',
      type: 'drums',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: '',
      rel_key_scale: '',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_BEAT_121_EURO.wav",
    },
    {
      id: 15,
      name: 'US_RD_BEAT_121_FMR',
      type: 'drums',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: '',
      rel_key_scale: '',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_BEAT_121_FMR.wav",
    },
    {
      id: 15,
      name: 'US_RD_BEAT_121_FMR',
      type: 'drums',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: '',
      rel_key_scale: '',
      bpm: 121,
      length: 4,
      url: "http://localhost:8080/audio/US_RD_BEAT_121_FMR.wav",
    },
    {
      id: 16,
      name: 'US_RD_SYNTH_121_Auckland_G#m',
      type: 'synth',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'G#m',
      rel_key_scale: 'B',
      bpm: 121,
      length: 16,
      url: "http://localhost:8080/audio/US_RD_SYNTH_121_Auckland_G#m.wav",
    },
    {
      id: 17,
      name: 'US_RD_SYNTH_121_Ayres_Dm',
      type: 'synth',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Dm',
      rel_key_scale: 'F',
      bpm: 121,
      length: 32,
      url: "http://localhost:8080/audio/US_RD_SYNTH_121_Ayres_Dm.wav",
    },
    {
      id: 18,
      name: 'US_RD_SYNTH_121_Bactra_A#',
      type: 'synth',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'A#',
      rel_key_scale: 'Gm',
      bpm: 121,
      length: 16,
      url: "http://localhost:8080/audio/US_RD_SYNTH_121_Bactra_A#.wav",
    },
    {
      id: 19,
      name: 'US_RD_SYNTH_121_Barcelona_G#m',
      type: 'synth',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'G#m',
      rel_key_scale: 'B',
      bpm: 121,
      length: 16,
      url: "http://localhost:8080/audio/US_RD_SYNTH_121_Barcelona_G#m.wav",
    },
    {
      id: 20,
      name: 'US_RD_SYNTH_121_Berlin_Cm',
      type: 'synth',
      genre: 'house',
      subgenre: 'raw deep',
      key_scale: 'Cm',
      rel_key_scale: 'D#',
      bpm: 121,
      length: 16,
      url: "http://localhost:8080/audio/US_RD_SYNTH_121_Berlin_Cm.wav",
    },
  ]);
};