module.exports = [
  { user_id: 1, set_id: 1, sound_id: 11 },
  { user_id: 1, set_id: 1, sound_id: 7 },
  { user_id: 1, set_id: 1, sound_id: 2 },
  { user_id: 1, set_id: 1, sound_id: 17 },
  { user_id: 1, set_id: 2, sound_id: 41 },
  { user_id: 1, set_id: 2, sound_id: 61 },
  { user_id: 1, set_id: 2, sound_id: 51 },
  { user_id: 1, set_id: 2, sound_id: 71 },
  { user_id: 1, set_id: 3, sound_id: 88 },
  { user_id: 1, set_id: 3, sound_id: 108 },
  { user_id: 1, set_id: 3, sound_id: 103 },
  { user_id: 1, set_id: 3, sound_id: 120 },
  { user_id: 1, set_id: 4, sound_id: 124 },
  { user_id: 1, set_id: 4, sound_id: 146 },
  { user_id: 1, set_id: 4, sound_id: 135 },
  { user_id: 1, set_id: 4, sound_id: 154 },
];
