module.exports = [
  {
    name: "US_RD_121_Bass_3AM_Fm",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Fm",
    rel_key_scale: "A",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_3AM_Fm.wav",
  },
  {
    name: "US_RD_121_Bass_90s_Dm",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_90s_Dm.wav",
  },
  {
    name: "US_RD_121_Bass_Ayres_Em",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_Ayres_Em.wav",
  },
  {
    name: "US_RD_121_Bass_barbara_A%23m",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "A%23m",
    rel_key_scale: "C%23",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_barbara_A%23m.wav",
  },
  {
    name: "US_RD_121_Bass_barcelona_Am",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Fm",
    rel_key_scale: "G%23",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_barcelona_Am.wav",
  },
  {
    name: "US_RD_121_Acamar_A",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Acamar_A.wav",
  },
  {
    name: "US_RD_121_Achird_Dm",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Achird_Dm.wav",
  },
  {
    name: "US_RD_121_Acrab_Bm",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Bm",
    rel_key_scale: "D",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Acrab_Bm.wav",
  },
  {
    name: "US_RD_121_Acrux_Cm",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Acrux_Cm.wav",
  },
  {
    name: "US_RD_121_Acubens_A",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Acubens_A.wav",
  },
  {
    name: "US_RD_BEAT_121_909",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_909.wav",
  },
  {
    name: "US_RD_BEAT_121_BEAT",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_BEAT.wav",
  },
  {
    name: "US_RD_BEAT_121_DRUGS",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_DRUGS.wav",
  },
  {
    name: "US_RD_BEAT_121_EURO",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_EURO.wav",
  },
  {
    name: "US_RD_BEAT_121_FMR",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_FMR.wav",
  },
  {
    name: "US_RD_SYNTH_121_Auckland_G%23m",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Auckland_G%23m.wav",
  },
  {
    name: "US_RD_SYNTH_121_Ayres_Dm",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 121,
    length: 32,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Ayres_Dm.wav",
  },
  {
    name: "US_RD_SYNTH_121_Bactra_A%23",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "A%23",
    rel_key_scale: "Gm",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Bactra_A%23.wav",
  },
  {
    name: "US_RD_SYNTH_121_Barcelona_G%23m",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Barcelona_G%23m.wav",
  },
  {
    name: "US_RD_SYNTH_121_Berlin_Cm",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Berlin_Cm.wav",
  },
  {
    name: "US_RD_121_Bass_Bassa_G%23",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "G%23",
    rel_key_scale: "Fm",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_Bassa_G%23.wav",
  },
  {
    name: "US_RD_121_Bass_black_Am",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_black_Am.wav",
  },
  {
    name: "US_RD_121_Bass_calibula_C%23m",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "C%23m",
    rel_key_scale: "E",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_calibula_C%23m.wav",
  },
  {
    name: "US_RD_121_Bass_Calipso_G%23m",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_Calipso_G%23m.wav",
  },
  {
    name: "US_RD_121_Bass_Casablanca_B",
    type: "bass",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "B",
    rel_key_scale: "G%23m",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_121_Bass_Casablanca_B.wav",
  },
  {
    name: "US_RD_121_Andromeda_Dm",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Andromeda_Dm.wav",
  },
  {
    name: "US_RD_121_antar_Em",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_antar_Em.wav",
  },
  {
    name: "US_RD_121_Aquila_G",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "G",
    rel_key_scale: "Em",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Aquila_G.wav",
  },
  {
    name: "US_RD_121_Asterion_Cm",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Asterion_Cm.wav",
  },
  {
    name: "US_RD_121_Atlas_Cm",
    type: "harmony",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 121,
    length: 8,
    url: "http://localhost:8080/audio/US_RD_121_Atlas_Cm.wav",
  },
  {
    name: "US_RD_BEAT_121_LA",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_LA.wav",
  },
  {
    name: "US_RD_BEAT_121_HAUSER",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_HAUSER.wav",
  },
  {
    name: "US_RD_BEAT_121_HAUZ",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_HAUZ.wav",
  },
  {
    name: "US_RD_BEAT_121_IINYUOUR",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_IINYUOUR.wav",
  },
  {
    name: "US_RD_BEAT_121_JAY",
    type: "drums",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "",
    rel_key_scale: "",
    bpm: 121,
    length: 4,
    url: "http://localhost:8080/audio/US_RD_BEAT_121_JAY.wav",
  },
  {
    name: "US_RD_SYNTH_121_Betty_C%23",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "C%23",
    rel_key_scale: "A%23m",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Betty_C%23.wav",
  },
  {
    name: "US_RD_SYNTH_121_Blazzers_G%23m",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Blazzers_G%23m.wav",
  },
  {
    name: "US_RD_SYNTH_121_Bling_Bm",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Bm",
    rel_key_scale: "D",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Bling_Bm.wav",
  },
  {
    name: "US_RD_SYNTH_121_Bru_Cm",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 121,
    length: 32,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Bru_Cm.wav",
  },
  {
    name: "US_RD_SYNTH_121_Buenavista_Dm",
    type: "synth",
    genre: "house",
    subgenre: "raw_deep",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 121,
    length: 16,
    url: "http://localhost:8080/audio/US_RD_SYNTH_121_Buenavista_Dm.wav",
  },
  {
    name: "US_DJH_Drum_118_absent_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_absent_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_bounds_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_bounds_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_call_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_call_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_cuz_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_cuz_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_dont_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_dont_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_earth_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_earth_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_frozen_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_frozen_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_grant_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_grant_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_huff_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_huff_FULL.wav",
  },
  {
    name: "US_DJH_Drum_118_inc_FULL",
    type: "drums",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "",
    rel_key_scale: "",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Drum_118_inc_FULL.wav",
  },
  {
    name: "US_DJH_Bass_118_absent_Bbm",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A%23m",
    rel_key_scale: "C%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_absent_Bbm.wav",
  },
  {
    name: "US_DJH_Bass_118_bounds_A",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_bounds_A.wav",
  },
  {
    name: "US_DJH_Bass_118_cuz_Bm",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Bm",
    rel_key_scale: "D",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_cuz_Bm.wav",
  },
  {
    name: "US_DJH_Bass_118_dont_A",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_dont_A.wav",
  },
  {
    name: "US_DJH_Bass_118_earth_Dbm",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "C%23m",
    rel_key_scale: "E",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_earth_Dbm.wav",
  },
  {
    name: "US_DJH_Bass_118_freack_Am",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_freack_Am.wav",
  },
  {
    name: "US_DJH_Bass_118_gear_Bb",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A%23",
    rel_key_scale: "Gm",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_gear_Bb.wav",
  },
  {
    name: "US_DJH_Bass_118_heard_A",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_heard_A.wav",
  },
  {
    name: "US_DJH_Bass_118_heard2_Cm",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_heard2_Cm.wav",
  },
  {
    name: "US_DJH_Bass_118_igloo_Am",
    type: "bass",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Bass_118_igloo_Am.wav",
  },
  {
    name: "US_DJH_Key_118_absent_Abm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_absent_Abm.wav",
  },
  {
    name: "US_DJH_Key_118_bounds_Gm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_bounds_Gm.wav",
  },
  {
    name: "US_DJH_Key_118_cuz_Bm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Bm",
    rel_key_scale: "D",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_cuz_Bm.wav",
  },
  {
    name: "US_DJH_Key_118_cuz_Abm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_cuz_Abm.wav",
  },
  {
    name: "US_DJH_Key_118_earth_Am",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Key_118_earth_Am.wav",
  },
  {
    name: "US_DJH_Key_118_freack_C",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "C",
    rel_key_scale: "Am",
    bpm: 118,
    length: 4,
    url: "http://localhost:8080/audio/US_DJH_Key_118_freack_C.wav",
  },
  {
    name: "US_DJH_Key_118_gear_Bbm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A%23m",
    rel_key_scale: "C%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_gear_Bbm.wav",
  },
  {
    name: "US_DJH_Key_118_heard_Cm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_heard_Cm.wav",
  },
  {
    name: "US_DJH_Key_118_heard2_Cm",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_heard2_Cm.wav",
  },
  {
    name: "US_DJH_Key_118_igloo_Db",
    type: "harmony",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "C%23",
    rel_key_scale: "A%23m",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Key_118_igloo_Db.wav",
  },
  {
    name: "US_DJH_Synth_118_absent_Abm",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_absent_Abm.wav",
  },
  {
    name: "US_DJH_Synth_118_absent_Bbm",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A%23m",
    rel_key_scale: "C%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_absent_Bbm.wav",
  },
  {
    name: "US_DJH_Synth_118_absent_Ebm",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "D%23m",
    rel_key_scale: "F%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_absent_Ebm.wav",
  },
  {
    name: "US_DJH_Synth_118_absent_F",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "F",
    rel_key_scale: "Dm",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_absent_F.wav",
  },
  {
    name: "US_DJH_Synth_118_bounds_Am",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_bounds_Am.wav",
  },
  {
    name: "US_DJH_Synth_118_bounds2_Am",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_bounds2_Am.wav",
  },
  {
    name: "US_DJH_Synth_118_crying_A",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_crying_A.wav",
  },
  {
    name: "US_DJH_Synth_118_dear_Am",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_dear_Am.wav",
  },
  {
    name: "US_DJH_Synth_118_empty_Eb",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "D%23",
    rel_key_scale: "Cm",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_empty_Eb.wav",
  },
  {
    name: "US_DJH_Synth_118_fresh_Eb",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "D%23",
    rel_key_scale: "Cm",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_fresh_Eb.wav",
  },
  {
    name: "US_DJH_Synth_118_gear_Bbm",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "A%23m",
    rel_key_scale: "C%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_gear_Bbm.wav",
  },
  {
    name: "US_DJH_Synth_118_heard_Cm",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_heard_Cm.wav",
  },
  {
    name: "US_DJH_Synth_118_igloo_Cm",
    type: "synth",
    genre: "house",
    subgenre: "jazz_house",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 118,
    length: 8,
    url: "http://localhost:8080/audio/US_DJH_Synth_118_igloo_Cm.wav",
  },
  {
    name: "US_DDT_Drm_114_Ball_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Ball_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Bell_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Bell_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Black_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Black_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Bloob_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Bloob_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Blues_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Blues_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Bold_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Bold_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Break_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Break_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Call_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Call_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Dice_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Dice_full.wav",
  },
  {
    name: "US_DDT_Drm_114_Done_full",
    type: "drums",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "",
    rel_key_scale: "",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Drm_114_Done_full.wav",
  },
  {
    name: "US_DDT_Bass_114_Addiction_D%23m",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "D%23m",
    rel_key_scale: "F%23",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Addiction_D%23m.wav",
  },
  {
    name: "US_DDT_Bass_114_Airport_Em",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Airport_Em.wav",
  },
  {
    name: "US_DDT_Bass_114_Autoban_Em",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Autoban_Em.wav",
  },
  {
    name: "US_DDT_Bass_114_Bar_E",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "E",
    rel_key_scale: "C%23m",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Bar_E.wav",
  },
  {
    name: "US_DDT_Bass_114_Bell_Em",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Bell_Em.wav",
  },
  {
    name: "US_DDT_Bass_114_Blue_Dm",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Fm",
    rel_key_scale: "F",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Blue_Dm.wav",
  },
  {
    name: "US_DDT_Bass_114_Champions_Fm",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Fm",
    rel_key_scale: "G%23",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Champions_Fm.wav",
  },
  {
    name: "US_DDT_Bass_114_Flag_Gm",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Flag_Gm.wav",
  },
  {
    name: "US_DDT_Bass_114_Flat_G%23m",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Flat_G%23m.wav",
  },
  {
    name: "US_DDT_Bass_114_Fluo_Cm",
    type: "bass",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 114,
    length: 4,
    url: "http://localhost:8080/audio/US_DDT_Bass_114_Fluo_Cm.wav",
  },
  {
    name: "US_DDT_Pad_114_After_C%23m",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "C%23m",
    rel_key_scale: "E",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_After_C%23m.wav",
  },
  {
    name: "US_DDT_Pad_114_Crazy_Gm",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Crazy_Gm.wav",
  },
  {
    name: "US_DDT_Pad_114_Deep_Dm",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Deep_Dm.wav",
  },
  {
    name: "US_DDT_Pad_114_Distribution_Em",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Distribution_Em.wav",
  },
  {
    name: "US_DDT_Pad_114_Earth_Cm",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Earth_Cm.wav",
  },
  {
    name: "US_DDT_Pad_114_File_A",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "A",
    rel_key_scale: "F%23m",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_File_A.wav",
  },
  {
    name: "US_DDT_Pad_114_Hell_D",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "D",
    rel_key_scale: "Bm",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Hell_D.wav",
  },
  {
    name: "US_DDT_Pad_114_Hulk_C",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "C",
    rel_key_scale: "Am",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Hulk_C.wav",
  },
  {
    name: "US_DDT_Pad_114_Jelly_F",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "F",
    rel_key_scale: "Dm",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Jelly_F.wav",
  },
  {
    name: "US_DDT_Pad_114_Long_E",
    type: "harmony",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "E",
    rel_key_scale: "C%23m",
    bpm: 114,
    length: 17,
    url: "http://localhost:8080/audio/US_DDT_Pad_114_Long_E.wav",
  },
  {
    name: "US_DDT_Synth_114_Bell_C%23m",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "C%23m",
    rel_key_scale: "E",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Bell_C%23m.wav",
  },
  {
    name: "US_DDT_Synth_114_Bounce_Gm",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Bounce_Gm.wav",
  },
  {
    name: "US_DDT_Synth_114_Bread_Gm",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Bread_Gm.wav",
  },
  {
    name: "US_DDT_Synth_114_Buzz_Dm",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Buzz_Dm.wav",
  },
  {
    name: "US_DDT_Synth_114_Coffe_Em",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Em",
    rel_key_scale: "G",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Coffe_Em.wav",
  },
  {
    name: "US_DDT_Synth_114_Cool_G%23m",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Cool_G%23m.wav",
  },
  {
    name: "US_DDT_Synth_114_Dell_Cm",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Cm",
    rel_key_scale: "D%23",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Dell_Cm.wav",
  },
  {
    name: "US_DDT_Synth_114_Download_G%23m",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "G%23m",
    rel_key_scale: "B",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Download_G%23m.wav",
  },
  {
    name: "US_DDT_Synth_114_Dragon_C%23m",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "C%23m",
    rel_key_scale: "E",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Dragon_C%23m.wav",
  },
  {
    name: "US_DDT_Synth_114_Est_Gm",
    type: "synth",
    genre: "techno",
    subgenre: "dub_techno",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 114,
    length: 8,
    url: "http://localhost:8080/audio/US_DDT_Synth_114_Est_Gm.wav",
  },
  {
    name: "US_drm75_cassette_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_cassette_ful.wav",
  },
  {
    name: "US_drm75_cavern_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_cavern_ful.wav",
  },
  {
    name: "US_drm75_chytry_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_chytry_ful.wav",
  },
  {
    name: "US_drm75_digitakt_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_digitakt_ful.wav",
  },
  {
    name: "US_drm75_driven_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_driven_ful.wav",
  },
  {
    name: "US_drm75_modchine_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_modchine_ful.wav",
  },
  {
    name: "US_drm75_rumi_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_rumi_ful.wav",
  },
  {
    name: "US_drm75_soviet_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_soviet_ful.wav",
  },
  {
    name: "US_drm75_volcasam_ful",
    type: "drums",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "",
    rel_key_scale: "",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_drm75_volcasam_ful.wav",
  },
  {
    name: "US_bs75_101force_Gm",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_bs75_101force_Gm.wav",
  },
  {
    name: "US_bs75_101reso_Am",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_bs75_101reso_Am.wav",
  },
  {
    name: "US_bs75_brassy_Dm",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_bs75_brassy_Dm.wav",
  },
  {
    name: "US_bs75_brody_Gm",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_bs75_brody_Gm.wav",
  },
  {
    name: "US_bs75_dane_Am",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_bs75_dane_Am.wav",
  },
  {
    name: "US_bs75_electric_C",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "C",
    rel_key_scale: "Am",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_bs75_electric_C.wav",
  },
  {
    name: "US_bs75_fuzzhead_Gm",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_bs75_fuzzhead_Gm.wav",
  },
  {
    name: "US_bs75_grainbuzz_Am",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_bs75_grainbuzz_Am.wav",
  },
  {
    name: "US_bs75_grainbuzz_lowpass_Am",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_bs75_grainbuzz_lowpass_Am.wav",
  },
  {
    name: "US_bs75_microphase_Gm",
    type: "bass",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Gm",
    rel_key_scale: "A%23",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_bs75_microphase_Gm.wav",
  },
  {
    name: "US_pad75_aerial_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 26,
    url: "http://localhost:8080/audio/US_pad75_aerial_Dm.wav",
  },
  {
    name: "US_pad75_aerial_lo_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 26,
    url: "http://localhost:8080/audio/US_pad75_aerial_lo_Dm.wav",
  },
  {
    name: "US_pad75_creampad_Am",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_creampad_Am.wav",
  },
  {
    name: "US_pad75_fluttercassette_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_fluttercassette_Dm.wav",
  },
  {
    name: "US_pad75_gritty_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_gritty_Dm.wav",
  },
  {
    name: "US_pad75_lighthouse_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_lighthouse_Dm.wav",
  },
  {
    name: "US_pad75_lighthouse2_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_lighthouse2_Dm.wav",
  },
  {
    name: "US_pad75_northern_C",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "C",
    rel_key_scale: "Am",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_northern_C.wav",
  },
  {
    name: "US_pad75_resotrem_Am",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_pad75_resotrem_Am.wav",
  },
  {
    name: "US_pad75_reverser_Dm",
    type: "harmony",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_pad75_reverser_Dm.wav",
  },
  {
    name: "US_syn75_crusty_Dm",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_syn75_crusty_Dm.wav",
  },
  {
    name: "US_syn75_echopiano_Dm",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 26,
    url: "http://localhost:8080/audio/US_syn75_echopiano_Dm.wav",
  },
  {
    name: "US_syn75_filterstrings_Cm",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Cm",
    rel_key_scale: "A",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_syn75_filterstrings_Cm.wav",
  },
  {
    name: "US_syn75_iceland_Am",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_syn75_iceland_Am.wav",
  },
  {
    name: "US_syn75_intermodulate_E",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "E",
    rel_key_scale: "C%23m",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_syn75_intermodulate_E.wav",
  },
  {
    name: "US_syn75_lofiairport_E",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "E",
    rel_key_scale: "C%23m",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_syn75_lofiairport_E.wav",
  },
  {
    name: "US_syn75_minilogue_Dm",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_syn75_minilogue_Dm.wav",
  },
  {
    name: "US_syn75_miniorgan_Am",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Am",
    rel_key_scale: "C",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_syn75_miniorgan_Am.wav",
  },
  {
    name: "US_syn75_minipluck_Dm",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "CF",
    bpm: 75,
    length: 6,
    url: "http://localhost:8080/audio/US_syn75_minipluck_Dm.wav",
  },
  {
    name: "US_syn75_ministrings_Dm",
    type: "synth",
    genre: "electronica",
    subgenre: "dreamtronica",
    key_scale: "Dm",
    rel_key_scale: "F",
    bpm: 75,
    length: 13,
    url: "http://localhost:8080/audio/US_syn75_ministrings_Dm.wav",
  },
];
